-- Message Handling SQL Examples
-- Validated against live IBM i system

-- Read system operator message queue
SELECT MESSAGE_ID, MESSAGE_TYPE, MESSAGE_TEXT,
       SEVERITY, FROM_USER, FROM_JOB, MESSAGE_TIMESTAMP
  FROM QSYS2.MESSAGE_QUEUE_INFO
  WHERE MESSAGE_QUEUE_NAME = 'QSYSOPR'
    AND MESSAGE_QUEUE_LIBRARY = 'QSYS'
  ORDER BY MESSAGE_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- Read high-severity messages (errors 40+)
SELECT MESSAGE_ID, MESSAGE_TYPE, MESSAGE_TEXT, SEVERITY,
       FROM_USER, MESSAGE_TIMESTAMP
  FROM QSYS2.MESSAGE_QUEUE_INFO
  WHERE MESSAGE_QUEUE_NAME = 'QSYSOPR'
    AND MESSAGE_QUEUE_LIBRARY = 'QSYS'
    AND SEVERITY >= 40
  ORDER BY MESSAGE_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- Count messages by severity in QSYSOPR
SELECT SEVERITY, COUNT(*) AS MESSAGE_COUNT,
       MIN(MESSAGE_TIMESTAMP) AS EARLIEST,
       MAX(MESSAGE_TIMESTAMP) AS LATEST
  FROM QSYS2.MESSAGE_QUEUE_INFO
  WHERE MESSAGE_QUEUE_NAME = 'QSYSOPR'
    AND MESSAGE_QUEUE_LIBRARY = 'QSYS'
  GROUP BY SEVERITY
  ORDER BY SEVERITY DESC;

-- Read system history log
SELECT MESSAGE_ID, MESSAGE_TYPE, MESSAGE_TEXT,
       SEVERITY, FROM_USER, FROM_JOB, FROM_PROGRAM, MESSAGE_TIMESTAMP
  FROM TABLE(QSYS2.HISTORY_LOG_INFO())
  ORDER BY MESSAGE_TIMESTAMP DESC
  FETCH FIRST 100 ROWS ONLY;

-- Search history log for a specific message ID
SELECT MESSAGE_ID, MESSAGE_TEXT, SEVERITY,
       FROM_USER, FROM_JOB, MESSAGE_TIMESTAMP
  FROM TABLE(QSYS2.HISTORY_LOG_INFO())
  WHERE MESSAGE_ID LIKE 'CPF%'
    AND SEVERITY >= 30
  ORDER BY MESSAGE_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- View system reply list
SELECT SEQUENCE_NUMBER, MESSAGE_ID, MESSAGE_REPLY,
       COMPARISON_DATA, DUMP_JOB
  FROM QSYS2.REPLY_LIST_INFO
  ORDER BY SEQUENCE_NUMBER;

-- Look up a message definition
SELECT MESSAGE_ID, MESSAGE_TEXT, SEVERITY,
       REPLY_TYPE, DEFAULT_REPLY
  FROM QSYS2.MESSAGE_FILE_DATA
  WHERE MESSAGE_FILE = 'QCPFMSG'
    AND MESSAGE_FILE_LIBRARY = 'QSYS'
    AND MESSAGE_ID = 'CPF1124';

-- Search message file by prefix
SELECT MESSAGE_ID, MESSAGE_TEXT, SEVERITY
  FROM QSYS2.MESSAGE_FILE_DATA
  WHERE MESSAGE_FILE = 'QCPFMSG'
    AND MESSAGE_FILE_LIBRARY = 'QSYS'
    AND MESSAGE_ID LIKE 'CPF18%'
  ORDER BY MESSAGE_ID
  FETCH FIRST 50 ROWS ONLY;
