-- Product SQL Examples
-- Validated against live IBM i system

-- Installed software products
SELECT PRODUCT_ID, PRODUCT_OPTION, RELEASE_LEVEL,
       INSTALLED, SYMBOLIC_LOAD_STATE, LOAD_ERROR,
       TEXT_DESCRIPTION
  FROM QSYS2.SOFTWARE_PRODUCT_INFO
  WHERE INSTALLED = 'YES'
  ORDER BY PRODUCT_ID, PRODUCT_OPTION
  FETCH FIRST 50 ROWS ONLY;

-- Specific product details
SELECT PRODUCT_ID, PRODUCT_OPTION, LOAD_ID, LOAD_TYPE,
       RELEASE_LEVEL, SYMBOLIC_LOAD_STATE,
       TEXT_DESCRIPTION, RELEASE_DATE
  FROM QSYS2.SOFTWARE_PRODUCT_INFO
  WHERE PRODUCT_ID = '5770SS1'
  ORDER BY PRODUCT_OPTION, LOAD_ID;

-- Products with load errors
SELECT PRODUCT_ID, PRODUCT_OPTION, RELEASE_LEVEL,
       SYMBOLIC_LOAD_STATE, LOAD_ERROR, TEXT_DESCRIPTION
  FROM QSYS2.SOFTWARE_PRODUCT_INFO
  WHERE LOAD_ERROR = 'YES'
  ORDER BY PRODUCT_ID;

-- License information
SELECT PRODUCT_ID, RELEASE_LEVEL, PRODUCT_TEXT,
       USAGE_LIMIT, USAGE_COUNT, PEAK_USAGE,
       COMPLIANCE_TYPE, LICENSE_EXPIRATION
  FROM QSYS2.LICENSE_INFO
  WHERE INSTALLED = 'YES'
  ORDER BY PRODUCT_ID, FEATURE_ID;

-- Unsupported or incompatible products
SELECT PRODUCT_ID, PRODUCT_OPTION, RELEASE_LEVEL,
       SUPPORTED, COMPATIBLE, LOAD_ERROR, TEXT_DESCRIPTION
  FROM QSYS2.SOFTWARE_PRODUCT_INFO
  WHERE INSTALLED = 'YES'
    AND (SUPPORTED = 'NO' OR COMPATIBLE = 'NO' OR LOAD_ERROR = 'YES')
  ORDER BY PRODUCT_ID;
