-- IFS SQL Examples
-- Validated against live IBM i system

-- List contents of root directory
SELECT PATH_NAME, OBJECT_TYPE, DATA_SIZE, OBJECT_OWNER, CREATE_TIMESTAMP
  FROM TABLE(QSYS2.IFS_OBJECT_STATISTICS(
    START_PATH_NAME => '/',
    SUBTREE_DIRECTORIES => 'NO'))
  ORDER BY OBJECT_TYPE, PATH_NAME
  FETCH FIRST 100 ROWS ONLY;

-- Search for .log files under /tmp
SELECT PATH_NAME, OBJECT_TYPE, DATA_SIZE, OBJECT_OWNER, LAST_USED_TIMESTAMP
  FROM TABLE(QSYS2.IFS_OBJECT_STATISTICS(
    START_PATH_NAME => '/tmp',
    SUBTREE_DIRECTORIES => 'YES'))
  WHERE PATH_NAME LIKE '%.log%'
  FETCH FIRST 100 ROWS ONLY;

-- Find largest stream files in /home
SELECT PATH_NAME, DATA_SIZE, ALLOCATED_SIZE, OBJECT_OWNER
  FROM TABLE(QSYS2.IFS_OBJECT_STATISTICS(
    START_PATH_NAME => '/home',
    SUBTREE_DIRECTORIES => 'YES'))
  WHERE OBJECT_TYPE = '*STMF'
  ORDER BY DATA_SIZE DESC
  FETCH FIRST 50 ROWS ONLY;

-- Check authorities on a specific path
SELECT PATH_NAME, AUTHORIZATION_NAME, DATA_AUTHORITY,
       DATA_READ, DATA_ADD, DATA_UPDATE, DATA_DELETE, DATA_EXECUTE
  FROM TABLE(QSYS2.IFS_OBJECT_PRIVILEGES(PATH_NAME => '/tmp'))
  ORDER BY AUTHORIZATION_NAME;

-- Read a text file
SELECT LINE_NUMBER, LINE
  FROM TABLE(QSYS2.IFS_READ(
    PATH_NAME => '/etc/hosts',
    END_OF_LINE => 'ANY',
    MAXIMUM_LINE_LENGTH => 1000))
  FETCH FIRST 200 ROWS ONLY;

-- Show locks on a file
SELECT PATH_NAME, JOB_NAME, RO_COUNT, WO_COUNT, RW_COUNT,
       CHECKED_OUT, CHECKED_OUT_USER_NAME
  FROM TABLE(QSYS2.IFS_OBJECT_LOCK_INFO(PATH_NAME => '/tmp'))
  ORDER BY JOB_NAME;

-- List NetServer shares
SELECT SERVER_SHARE_NAME, SHARE_TYPE, PATH_NAME, PERMISSIONS,
       MAXIMUM_CONNECTIONS, CURRENT_CONNECTIONS
  FROM QSYS2.SERVER_SHARE_INFO
  ORDER BY SHARE_TYPE, SERVER_SHARE_NAME;
