-- Security SQL Examples
-- Validated against live IBM i system

-- Users with limited capabilities
SELECT AUTHORIZATION_NAME, STATUS, SPECIAL_AUTHORITIES,
       USER_CLASS_NAME, TEXT_DESCRIPTION
  FROM QSYS2.USER_INFO_BASIC
  WHERE LIMIT_CAPABILITIES = '*YES'
  ORDER BY AUTHORIZATION_NAME;

-- Users with *ALLOBJ or *SAVSYS special authorities
SELECT AUTHORIZATION_NAME, SPECIAL_AUTHORITY,
       AUTHORITY_SOURCE, STATUS
  FROM SYSTOOLS.SPECIAL_AUTHORITY_DATA_MART
  WHERE SPECIAL_AUTHORITY IN ('*ALLOBJ', '*SAVSYS')
  ORDER BY AUTHORIZATION_NAME;

-- User profiles vulnerable to impersonation
SELECT SYSTEM_OBJECT_NAME AS USER_NAME, OBJECT_AUTHORITY, OWNER
  FROM QSYS2.OBJECT_PRIVILEGES
  WHERE SYSTEM_OBJECT_SCHEMA = 'QSYS'
    AND OBJECT_TYPE = '*USRPRF'
    AND AUTHORIZATION_NAME = '*PUBLIC'
    AND OBJECT_AUTHORITY <> '*EXCLUDE'
    AND SYSTEM_OBJECT_NAME NOT IN ('QDBSHR', 'QDBSHRDO', 'QDOC', 'QTMPLPD');

-- *PUBLIC authority on dangerous commands
SELECT SYSTEM_OBJECT_NAME, OBJECT_TYPE, OBJECT_AUTHORITY
  FROM QSYS2.OBJECT_PRIVILEGES
  WHERE SYSTEM_OBJECT_SCHEMA = 'QSYS'
    AND OBJECT_TYPE = '*CMD'
    AND SYSTEM_OBJECT_NAME IN ('ADDPFTRG', 'CRTPGM', 'CRTSRVPGM', 'SAVOBJ', 'SAVLIB', 'CRTDUPOBJ', 'CPYF')
    AND AUTHORIZATION_NAME = '*PUBLIC';

-- Group profile members
SELECT GROUP_PROFILE_NAME, USER_PROFILE_NAME, USER_TEXT
  FROM QSYS2.GROUP_PROFILE_ENTRIES
  ORDER BY GROUP_PROFILE_NAME, USER_PROFILE_NAME
  FETCH FIRST 50 ROWS ONLY;

-- Commands allowed for limited users
SELECT COMMAND_NAME, COMMAND_LIBRARY, TEXT_DESCRIPTION
  FROM QSYS2.COMMAND_INFO
  WHERE ALLOW_LIMITED_USER = 'YES'
  ORDER BY COMMAND_LIBRARY, COMMAND_NAME;

-- Function usage settings
SELECT FUNCTION_ID, USER_NAME, USAGE, USER_TYPE
  FROM QSYS2.FUNCTION_USAGE
  ORDER BY FUNCTION_ID, USER_NAME
  FETCH FIRST 50 ROWS ONLY;
