-- Journal SQL Examples
-- Validated against live IBM i system

-- List all journals with state and receiver info
SELECT JOURNAL_NAME, JOURNAL_LIBRARY, JOURNAL_TYPE, JOURNAL_STATE,
       ATTACHED_JOURNAL_RECEIVER_NAME, ATTACHED_JOURNAL_RECEIVER_LIBRARY,
       NUMBER_JOURNAL_RECEIVERS, TOTAL_SIZE_JOURNAL_RECEIVERS,
       JOURNALED_OBJECTS, JOURNAL_TEXT
  FROM QSYS2.JOURNAL_INFO
  ORDER BY JOURNAL_LIBRARY, JOURNAL_NAME
  FETCH FIRST 100 ROWS ONLY;

-- Journal receivers for a specific journal
SELECT JOURNAL_RECEIVER_NAME, JOURNAL_RECEIVER_LIBRARY,
       STATUS, SIZE, NUMBER_OF_JOURNAL_ENTRIES,
       ATTACH_TIMESTAMP, DETACH_TIMESTAMP,
       PREVIOUS_JOURNAL_RECEIVER, NEXT_JOURNAL_RECEIVER
  FROM QSYS2.JOURNAL_RECEIVER_INFO
  WHERE JOURNAL_NAME = 'QAUDJRN' AND JOURNAL_LIBRARY = 'QSYS'
  ORDER BY ATTACH_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- Objects journaled by the audit journal
SELECT OBJECT_NAME, OBJECT_LIBRARY, OBJECT_TYPE,
       JOURNAL_IMAGES, OMIT_JOURNAL_ENTRY
  FROM QSYS2.JOURNALED_OBJECTS
  WHERE JOURNAL_NAME = 'QAUDJRN' AND JOURNAL_LIBRARY = 'QSYS'
  ORDER BY OBJECT_LIBRARY, OBJECT_NAME;

-- Read recent audit journal entries (last 5 minutes)
SELECT ENTRY_TIMESTAMP, JOURNAL_CODE, JOURNAL_ENTRY_TYPE,
       OBJECT, OBJECT_TYPE, USER_NAME,
       JOB_NAME, PROGRAM_NAME
  FROM TABLE(QSYS2.DISPLAY_JOURNAL(
    JOURNAL_LIBRARY => 'QSYS',
    JOURNAL_NAME => 'QAUDJRN',
    STARTING_TIMESTAMP => CURRENT TIMESTAMP - 5 MINUTES))
  ORDER BY ENTRY_TIMESTAMP DESC
  FETCH FIRST 100 ROWS ONLY;

-- Find largest journal receivers
SELECT JOURNAL_RECEIVER_NAME, JOURNAL_RECEIVER_LIBRARY,
       JOURNAL_NAME, JOURNAL_LIBRARY, STATUS, SIZE
  FROM QSYS2.JOURNAL_RECEIVER_INFO
  ORDER BY SIZE DESC
  FETCH FIRST 20 ROWS ONLY;

-- Remote journal replication status
SELECT SOURCE_JOURNAL_LIBRARY, SOURCE_JOURNAL,
       REMOTE_DATABASE_NAME, REMOTE_JOURNAL_STATE, DELIVERY_MODE,
       ENTRIES_BEHIND, TIME_BEHIND
  FROM QSYS2.REMOTE_JOURNAL_INFO;

-- SMAPP access path protection status
SELECT SYSTEM_TABLE_SCHEMA, SYSTEM_TABLE_NAME, STATUS,
       INELIGIBLE_REASON, ESTIMATED_RECOVERY
  FROM QSYS2.SMAPP_ACCESS_PATHS
  ORDER BY SYSTEM_TABLE_SCHEMA, SYSTEM_TABLE_NAME;

-- Audit journal data mart build status
SELECT DATA_MART_LIBRARY, DATA_MART_TABLE, JOURNAL_ENTRY_TYPE,
       BUILD_START, BUILD_END, FAILURE_DETAIL
  FROM QSYS2.AUDIT_JOURNAL_DATA_MART_INFO
  ORDER BY DATA_MART_LIBRARY, DATA_MART_TABLE;
