-- Performance Monitoring SQL Examples
-- Validated against live IBM i system

-- Collection services configuration
SELECT ACTIVE_COLLECTION_LIBRARY, ACTIVE_COLLECTION_NAME,
       ACTIVE_COLLECTION_PROFILE, DEFAULT_COLLECTION_INTERVAL,
       RETENTION_DAYS, ENABLE_SYSTEM_MONITORING
  FROM QSYS2.COLLECTION_SERVICES_INFO;

-- Collection categories and intervals
SELECT cs_category, cs_interval
  FROM QSYS2.COLLECTION_SERVICES_INFO,
       LATERAL (SELECT * FROM JSON_TABLE(CATEGORY_LIST, 'lax $.category_list[*]'
       COLUMNS(cs_category CLOB(1K) CCSID 1208 PATH 'lax $."category"',
               cs_interval CLOB(1K) CCSID 1208 PATH 'lax $."interval"'))) a;

-- Named temporary storage buckets
SELECT GLOBAL_BUCKET_NAME, BUCKET_CURRENT_SIZE, BUCKET_PEAK_SIZE
  FROM QSYS2.SYSTMPSTG
  WHERE GLOBAL_BUCKET_NAME IS NOT NULL
  ORDER BY BUCKET_CURRENT_SIZE DESC;

-- Unnamed temporary storage total
SELECT SUM(BUCKET_CURRENT_SIZE) AS CURRENT_SIZE,
       SUM(BUCKET_PEAK_SIZE) AS PEAK_SIZE
  FROM QSYS2.SYSTMPSTG
  WHERE GLOBAL_BUCKET_NAME IS NULL;

-- Top temporary storage consumers by job
SELECT JOB_NAME, JOB_USER_NAME, JOB_NUMBER, JOB_STATUS,
       BUCKET_CURRENT_SIZE, BUCKET_PEAK_SIZE, BUCKET_LIMIT_SIZE
  FROM QSYS2.SYSTMPSTG
  WHERE JOB_NAME IS NOT NULL
  ORDER BY BUCKET_CURRENT_SIZE DESC
  FETCH FIRST 25 ROWS ONLY;

-- Disk I/O performance per unit
SELECT UNIT_NUMBER, ASP_NUMBER, DISK_TYPE,
       ELAPSED_IO_REQUESTS, ELAPSED_READ_REQUESTS,
       ELAPSED_WRITE_REQUESTS, ELAPSED_PERCENT_BUSY
  FROM QSYS2.SYSDISKSTAT
  WHERE ELAPSED_IO_REQUESTS > 0
  ORDER BY ELAPSED_PERCENT_BUSY DESC;

-- Memory pool performance with fault rates
SELECT POOL_NAME, CURRENT_SIZE,
       MAXIMUM_ACTIVE_THREADS, CURRENT_THREADS,
       ELAPSED_DATABASE_FAULTS, ELAPSED_NON_DATABASE_FAULTS,
       ELAPSED_TOTAL_FAULTS, ELAPSED_ACTIVE_TO_WAIT,
       TUNING_PRIORITY, TUNING_MINIMUM_SIZE, TUNING_MAXIMUM_SIZE
  FROM TABLE(QSYS2.MEMORY_POOL(RESET_STATISTICS => 'YES')) X
  ORDER BY ELAPSED_TOTAL_FAULTS DESC;
