-- Configuration SQL Examples
-- Validated against live IBM i system

-- All system values
SELECT SYSTEM_VALUE_NAME, CURRENT_NUMERIC_VALUE,
       CURRENT_CHARACTER_VALUE, CATEGORY, CHANGEABLE
  FROM QSYS2.SYSTEM_VALUE_INFO
  ORDER BY SYSTEM_VALUE_NAME
  FETCH FIRST 50 ROWS ONLY;

-- Specific system value
SELECT SYSTEM_VALUE_NAME, CURRENT_NUMERIC_VALUE,
       CURRENT_CHARACTER_VALUE, SHIPPED_DEFAULT_VALUE
  FROM QSYS2.SYSTEM_VALUE_INFO
  WHERE SYSTEM_VALUE_NAME = 'QSECURITY';

-- Security-related system values
SELECT SYSTEM_VALUE_NAME, CURRENT_NUMERIC_VALUE,
       CURRENT_CHARACTER_VALUE, SHIPPED_DEFAULT_VALUE
  FROM QSYS2.SYSTEM_VALUE_INFO
  WHERE SYSTEM_VALUE_NAME IN (
    'QSECURITY', 'QAUDCTL', 'QAUDLVL', 'QPWDEXPITV',
    'QPWDLVL', 'QMAXSIGN', 'QMAXSGNACN', 'QLMTSECOFR'
  )
  ORDER BY SYSTEM_VALUE_NAME;

-- Hardware resources
SELECT RESOURCE_NAME, RESOURCE_CATEGORY, STATUS,
       DEVICE_TYPE, DEVICE_MODEL, SERIAL_NUMBER
  FROM QSYS2.HARDWARE_RESOURCE_INFO
  ORDER BY RESOURCE_CATEGORY, RESOURCE_NAME
  FETCH FIRST 50 ROWS ONLY;

-- Configuration status
SELECT OBJECT_NAME, OBJECT_TYPE, OBJECT_ATTRIBUTE,
       STATUS, STATUS_DESCRIPTION, TEXT_DESCRIPTION
  FROM SYSTOOLS.CONFIGURATION_STATUS
  ORDER BY OBJECT_TYPE, OBJECT_NAME
  FETCH FIRST 50 ROWS ONLY;

-- Environment variables
SELECT ENVIRONMENT_VARIABLE_TYPE, ENVIRONMENT_VARIABLE_NAME,
       ENVIRONMENT_VARIABLE_VALUE
  FROM QSYS2.ENVIRONMENT_VARIABLE_INFO
  ORDER BY ENVIRONMENT_VARIABLE_TYPE, ENVIRONMENT_VARIABLE_NAME
  FETCH FIRST 50 ROWS ONLY;

-- Active JVMs
SELECT JOB_NAME, JOB_USER, JAVA_THREAD_COUNT,
       TOTAL_GC_TIME, CURRENT_HEAP_SIZE, MAX_HEAP_SIZE
  FROM QSYS2.JVM_INFO
  ORDER BY TOTAL_GC_TIME DESC
  FETCH FIRST 20 ROWS ONLY;
