-- Communication Examples for IBM i SQL Services
-- Category: COMMUNICATION

-- 1. Active connections sorted by traffic
SELECT REMOTE_ADDRESS, REMOTE_PORT, LOCAL_PORT,
       BYTES_SENT_REMOTELY, BYTES_RECEIVED_LOCALLY,
       TCP_STATE, BOUND_USER
  FROM QSYS2.NETSTAT_INFO
  WHERE TCP_STATE = 'ESTABLISHED'
  ORDER BY BYTES_SENT_REMOTELY + BYTES_RECEIVED_LOCALLY DESC
  FETCH FIRST 30 ROWS ONLY;

-- 2. Count of connections by state
SELECT TCP_STATE, COUNT(*) AS CONNECTION_COUNT
  FROM QSYS2.NETSTAT_INFO
  GROUP BY TCP_STATE
  ORDER BY CONNECTION_COUNT DESC;

-- 3. Remote connections (excluding loopback)
SELECT COUNT(REMOTE_ADDRESS) AS REMOTE_CONNECTIONS
  FROM QSYS2.NETSTAT_INFO
  WHERE TCP_STATE = 'ESTABLISHED'
    AND REMOTE_ADDRESS != '::1'
    AND REMOTE_ADDRESS != '127.0.0.1';

-- 4. Network interfaces
SELECT INTERNET_ADDRESS, LINE_DESCRIPTION,
       INTERFACE_STATUS, SUBNET_MASK, CONFIGURED_MTU
  FROM QSYS2.NETSTAT_INTERFACE_INFO
  ORDER BY INTERFACE_STATUS;

-- 5. Routing table
SELECT ROUTE_DESTINATION, SUBNET_MASK, NEXT_HOP,
       ROUTE_TYPE, ROUTE_PRECEDENCE
  FROM QSYS2.NETSTAT_ROUTE_INFO
  ORDER BY ROUTE_PRECEDENCE;

-- 6. HTTP server status
SELECT SERVER_NAME, SERVER_STATUS, LISTENING_PORT,
       SERVER_ROOT_DIRECTORY, AUTOSTART
  FROM QSYS2.HTTP_SERVER_INFO
  ORDER BY SERVER_STATUS;

-- 7. TCP/IP configuration
SELECT LOCAL_HOST_NAME, LOCAL_DOMAIN_NAME,
       HOST_VERSION, CLIENT_IP_ADDRESS
  FROM QSYS2.TCPIP_INFO;

-- 8. Network attributes
SELECT * FROM QSYS2.NETWORK_ATTRIBUTE_INFO;

-- 9. Time protocol servers
SELECT TIME_SERVER, PROTOCOL, POLL_INTERVAL,
       SERVER_STATUS, LAST_KNOWN_DIFFERENCE
  FROM QSYS2.TIME_PROTOCOL_INFO;

-- 10. Network jobs by traffic volume
SELECT JOB_NAME, REMOTE_ADDRESS, LOCAL_PORT,
       BYTES_SENT, BYTES_RECEIVED
  FROM QSYS2.NETSTAT_JOB_INFO
  ORDER BY BYTES_SENT + BYTES_RECEIVED DESC
  FETCH FIRST 20 ROWS ONLY;
