-- Java JVM SQL Examples
-- Validated against live IBM i system

-- List all active JVMs sorted by GC time
SELECT JOB_NAME, JOB_NAME_SHORT, JOB_USER, START_TIME,
       JAVA_THREAD_COUNT, TOTAL_GC_TIME, GC_CYCLE_NUMBER,
       JAVA_HOME, CURRENT_HEAP_SIZE, IN_USE_HEAP_SIZE, MAX_HEAP_SIZE
  FROM QSYS2.JVM_INFO
  ORDER BY TOTAL_GC_TIME DESC
  FETCH FIRST 50 ROWS ONLY;

-- Detailed JVM info with memory breakdown
SELECT JOB_NAME, JOB_USER, JAVA_HOME,
       CURRENT_HEAP_SIZE, IN_USE_HEAP_SIZE, MAX_HEAP_SIZE,
       MALLOC_MEMORY_SIZE, INTERNAL_MEMORY_SIZE,
       JIT_MEMORY_SIZE, SHARED_CLASS_SIZE
  FROM TABLE(QSYS2.JVM_INFO(WAIT_TIME => 10))
  ORDER BY IN_USE_HEAP_SIZE DESC;

-- Find JVMs using more than 80% of max heap
SELECT JOB_NAME, JOB_USER, JAVA_HOME,
       CURRENT_HEAP_SIZE, IN_USE_HEAP_SIZE, MAX_HEAP_SIZE,
       DECIMAL(DECIMAL(IN_USE_HEAP_SIZE, 15, 2) /
         DECIMAL(MAX_HEAP_SIZE, 15, 2) * 100, 5, 1) AS HEAP_USED_PCT
  FROM QSYS2.JVM_INFO
  WHERE MAX_HEAP_SIZE > 0
    AND DECIMAL(DECIMAL(IN_USE_HEAP_SIZE, 15, 2) /
         DECIMAL(MAX_HEAP_SIZE, 15, 2) * 100, 5, 1) >= 80
  ORDER BY IN_USE_HEAP_SIZE DESC;

-- JVMs with highest GC cycle counts
SELECT JOB_NAME, JOB_USER, TOTAL_GC_TIME, GC_CYCLE_NUMBER,
       CURRENT_HEAP_SIZE, IN_USE_HEAP_SIZE, MAX_HEAP_SIZE
  FROM QSYS2.JVM_INFO
  WHERE GC_CYCLE_NUMBER > 0
  ORDER BY GC_CYCLE_NUMBER DESC
  FETCH FIRST 20 ROWS ONLY;

-- Count JVMs by Java home directory
SELECT JAVA_HOME, COUNT(*) AS JVM_COUNT,
       SUM(IN_USE_HEAP_SIZE) AS TOTAL_HEAP_IN_USE
  FROM QSYS2.JVM_INFO
  GROUP BY JAVA_HOME
  ORDER BY JVM_COUNT DESC;
