-- Database Application SQL Examples
-- Validated against live IBM i system

-- Recent SQL errors
SELECT LOGGED_SQLCODE, LOGGED_SQLSTATE,
       PROGRAM_LIBRARY, PROGRAM_NAME, PROGRAM_TYPE,
       STATEMENT_OPERATION_DETAIL,
       NUMBER_OCCURRENCES, LOGGED_TIME, JOB_NAME,
       CAST(STATEMENT_TEXT AS VARCHAR(500)) AS STATEMENT_TEXT
  FROM QSYS2.SQL_ERROR_LOG
  ORDER BY LOGGED_TIME DESC
  FETCH FIRST 25 ROWS ONLY;

-- Most frequent SQL errors
SELECT LOGGED_SQLCODE, LOGGED_SQLSTATE,
       SUM(NUMBER_OCCURRENCES) AS TOTAL_OCCURRENCES,
       MAX(LOGGED_TIME) AS LAST_OCCURRENCE,
       COUNT(*) AS DISTINCT_PROGRAMS
  FROM QSYS2.SQL_ERROR_LOG
  GROUP BY LOGGED_SQLCODE, LOGGED_SQLSTATE
  ORDER BY TOTAL_OCCURRENCES DESC
  FETCH FIRST 20 ROWS ONLY;

-- Errors for a specific program
SELECT LOGGED_SQLCODE, LOGGED_SQLSTATE,
       NUMBER_OCCURRENCES, LOGGED_TIME,
       CAST(STATEMENT_TEXT AS VARCHAR(500)) AS STATEMENT_TEXT
  FROM QSYS2.SQL_ERROR_LOG
  WHERE PROGRAM_NAME = 'MYPGM' AND PROGRAM_LIBRARY = 'MYLIB'
  ORDER BY LOGGED_TIME DESC;

-- Parse a SQL statement to find referenced objects
SELECT NAME_TYPE, NAME, SCHEMA, USAGE_TYPE, SQL_STATEMENT_TYPE
  FROM TABLE(QSYS2.PARSE_STATEMENT(
    SQL_STATEMENT => 'SELECT A.COL1, B.COL2 FROM MYLIB.TABLE1 A JOIN MYLIB.TABLE2 B ON A.ID = B.ID'))
  ORDER BY SCHEMA, NAME;

-- Look up SQLCODE meaning
SELECT MESSAGE_ID, MESSAGE_TEXT, MESSAGE_SECOND_LEVEL_TEXT
  FROM TABLE(SYSTOOLS.SQLCODE_INFO(-204));

-- Delimit a SQL name (check if quoting needed)
SELECT 'ORDER' AS ORIGINAL_NAME,
       QSYS2.DELIMIT_NAME('ORDER') AS DELIMITED_NAME
  FROM SYSIBM.SYSDUMMY1;

-- System limits ordered by percentage used
SELECT LIMIT_CATEGORY, LIMIT_TYPE, SIZING_NAME,
       SCHEMA_NAME, OBJECT_NAME,
       CURRENT_VALUE, MAXIMUM_VALUE,
       CASE WHEN MAXIMUM_VALUE > 0
         THEN INTEGER(CURRENT_VALUE * 100 / MAXIMUM_VALUE)
         ELSE 0 END AS PCT_USED,
       LAST_CHANGE_TIMESTAMP
  FROM QSYS2.SYSLIMITS
  WHERE MAXIMUM_VALUE > 0
  ORDER BY PCT_USED DESC
  FETCH FIRST 25 ROWS ONLY;

-- System limits for a specific schema
SELECT LIMIT_CATEGORY, LIMIT_TYPE, SIZING_NAME,
       OBJECT_NAME, CURRENT_VALUE, MAXIMUM_VALUE
  FROM QSYS2.SYSLIMITS
  WHERE SCHEMA_NAME = 'MYLIB'
  ORDER BY CURRENT_VALUE DESC;
