-- Migrate While Active SQL Examples
-- Validated against live IBM i system

-- Check overall migration status
SELECT ENTRY_TYPE, SOURCE_NODE_STATE, COPY_NODE_STATE,
       MIGRATION_STAGE, MIGRATION_PHASE,
       MIGRATION_DETAIL_INFO_TEXT, SOURCE_NODE, COPY_NODE
  FROM QSYS2.MIGRATION_MANAGER_INFO
  ORDER BY ENTRY_TYPE;

-- Library objects being tracked for migration
SELECT LIBRARY_NAME, OBJECT_NAME, OBJECT_TYPE, TRACKING_STATE,
       OBJECT_SIZE, MIGRATION_START_TIME
  FROM QSYS2.LIBRARY_MIGRATION_LIST
  ORDER BY LIBRARY_NAME, OBJECT_NAME
  FETCH FIRST 100 ROWS ONLY;

-- IFS objects being tracked for migration
SELECT PATH_NAME, OBJECT_TYPE, TRACKING_STATE,
       OBJECT_SIZE, MIGRATION_START_TIME
  FROM QSYS2.IFS_MIGRATION_LIST
  ORDER BY PATH_NAME
  FETCH FIRST 100 ROWS ONLY;

-- Successfully migrated library objects (last 24 hours)
SELECT LIBRARY_NAME, OBJECT_NAME, OBJECT_TYPE,
       MIGRATION_START_TIME, MIGRATION_END_TIME,
       SUCCESSFUL_MIGRATION_COUNT, OBJECT_SIZE
  FROM QSYS2.MIGRATED_LIBRARY
  WHERE MIGRATION_END_TIME > CURRENT TIMESTAMP - 24 HOURS
  ORDER BY MIGRATION_END_TIME DESC;

-- Migration failures
SELECT LIBRARY_NAME, OBJECT_NAME, OBJECT_TYPE, TRACKING_STATE,
       FAILURE_JOB_NAME, FAILURE_MESSAGE
  FROM QSYS2.LIBRARY_MIGRATION_LIST
  WHERE FAILURE_MESSAGE <> ''
  ORDER BY MIGRATION_START_TIME DESC;

-- Data compression factors
SELECT COMPRESSION_TYPE, COMPRESSION_FACTOR,
       IFS_COMPRESSION_FACTOR, OS_COMPRESSION_FACTOR
  FROM SYSIBMADM.DATA_COMPRESSION_FACTOR
  ORDER BY COMPRESSION_TYPE;

-- Estimate final synchronization time
SELECT * FROM TABLE(QSYS2.ESTIMATE_FINAL_SYNCHRONIZATION_TIME());

-- Check network bandwidth (3 measurements)
SELECT * FROM TABLE(QSYS2.MIGRATION_NETWORK_BANDWIDTH(3));
