-- Spool File Management SQL Examples
-- Validated against live IBM i system

-- List output queues with most files
SELECT OUTPUT_QUEUE_LIBRARY_NAME, OUTPUT_QUEUE_NAME, OUTPUT_QUEUE_STATUS,
       NUMBER_OF_FILES, WRITER_JOB_NAME, TEXT_DESCRIPTION
  FROM QSYS2.OUTPUT_QUEUE_INFO
  ORDER BY NUMBER_OF_FILES DESC
  FETCH FIRST 20 ROWS ONLY;

-- List spool files in a specific output queue
SELECT SPOOLED_FILE_NAME, JOB_NAME, STATUS, TOTAL_PAGES, SIZE,
       USER_NAME, CREATE_TIMESTAMP
  FROM QSYS2.OUTPUT_QUEUE_ENTRIES
  WHERE OUTPUT_QUEUE_LIBRARY_NAME = 'QUSRSYS'
    AND OUTPUT_QUEUE_NAME = 'QEZJOBLOG'
  ORDER BY CREATE_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- System-wide spool file search by user
SELECT SPOOLED_FILE_NAME, JOB_NAME, STATUS, TOTAL_PAGES, SIZE,
       OUTPUT_QUEUE_LIBRARY_NAME, OUTPUT_QUEUE_NAME, CREATE_TIMESTAMP
  FROM QSYS2.OUTPUT_QUEUE_ENTRIES_BASIC
  WHERE USER_NAME = 'MYUSER'
  ORDER BY CREATE_TIMESTAMP DESC
  FETCH FIRST 100 ROWS ONLY;

-- Top spool storage consumers by user
SELECT USER_NAME, COUNT(*) AS TOTAL_FILES,
       SUM(TOTAL_PAGES) AS TOTAL_PAGES,
       SUM(SIZE) AS TOTAL_SIZE_BYTES
  FROM QSYS2.OUTPUT_QUEUE_ENTRIES_BASIC
  GROUP BY USER_NAME
  ORDER BY TOTAL_SIZE_BYTES DESC
  FETCH FIRST 20 ROWS ONLY;

-- Find spool files older than 90 days
SELECT SPOOLED_FILE_NAME, JOB_NAME, USER_NAME,
       CREATE_TIMESTAMP, SIZE, STATUS, OUTPUT_QUEUE_NAME
  FROM QSYS2.OUTPUT_QUEUE_ENTRIES_BASIC
  WHERE CREATE_TIMESTAMP < CURRENT_TIMESTAMP - 90 DAYS
  ORDER BY CREATE_TIMESTAMP ASC
  FETCH FIRST 100 ROWS ONLY;

-- Spool storage summary with status counts
SELECT COUNT(*) AS TOTAL_FILES,
       SUM(TOTAL_PAGES) AS TOTAL_PAGES,
       SUM(SIZE) AS TOTAL_SIZE,
       SUM(CASE WHEN STATUS = 'READY' THEN 1 ELSE 0 END) AS READY,
       SUM(CASE WHEN STATUS = 'HELD' THEN 1 ELSE 0 END) AS HELD,
       SUM(CASE WHEN STATUS = 'SAVED' THEN 1 ELSE 0 END) AS SAVED
  FROM QSYS2.OUTPUT_QUEUE_ENTRIES_BASIC;

-- Read spooled file content
SELECT ORDINAL_POSITION, SPOOLED_DATA
  FROM TABLE(SYSTOOLS.SPOOLED_FILE_DATA(
    JOB_NAME => '123456/MYUSER/MYJOB',
    SPOOLED_FILE_NAME => 'QPJOBLOG',
    SPOOLED_FILE_NUMBER => -1))
  ORDER BY ORDINAL_POSITION
  FETCH FIRST 200 ROWS ONLY;

-- Get spooled files for current job
SELECT SPOOLED_FILE_NAME, FILE_NUMBER, STATUS, TOTAL_PAGES,
       OUTPUT_QUEUE_LIBRARY_NAME, OUTPUT_QUEUE_NAME, CREATE_TIMESTAMP
  FROM TABLE(QSYS2.SPOOLED_FILE_INFO(JOB_NAME => '*'))
  ORDER BY FILE_NUMBER;

-- Printer file definitions
SELECT SYSTEM_TABLE_SCHEMA AS LIBRARY, SYSTEM_TABLE_NAME AS PRINTER_FILE,
       TABLE_TEXT AS DESCRIPTION
  FROM QSYS2.SYSTABLES
  WHERE FILE_TYPE = 'P'
  ORDER BY SYSTEM_TABLE_SCHEMA, SYSTEM_TABLE_NAME;
