-- PTF Management SQL Examples
-- Validated against live IBM i system

-- Check PTF group currency for current release
WITH iLevel(iVersion, iRelease) AS (
  SELECT OS_VERSION, OS_RELEASE FROM SYSIBMADM.ENV_SYS_INFO
)
SELECT P.PTF_GROUP_CURRENCY, P.PTF_GROUP_ID, P.PTF_GROUP_TITLE,
       P.PTF_GROUP_LEVEL_INSTALLED, P.PTF_GROUP_LEVEL_AVAILABLE,
       (P.PTF_GROUP_LEVEL_AVAILABLE - P.PTF_GROUP_LEVEL_INSTALLED) AS LEVELS_BEHIND
  FROM iLevel, SYSTOOLS.GROUP_PTF_CURRENCY P
  WHERE PTF_GROUP_RELEASE = 'R' CONCAT iVersion CONCAT iRelease CONCAT '0'
  ORDER BY LEVELS_BEHIND DESC;

-- PTF currency summary
WITH iLevel(iVersion, iRelease) AS (
  SELECT OS_VERSION, OS_RELEASE FROM SYSIBMADM.ENV_SYS_INFO
)
SELECT PTF_GROUP_CURRENCY, COUNT(*) AS CNT
  FROM iLevel, SYSTOOLS.GROUP_PTF_CURRENCY P
  WHERE PTF_GROUP_RELEASE = 'R' CONCAT iVersion CONCAT iRelease CONCAT '0'
  GROUP BY PTF_GROUP_CURRENCY;

-- List all installed PTF groups
SELECT PTF_GROUP_NAME, PTF_GROUP_DESCRIPTION,
       PTF_GROUP_LEVEL, PTF_GROUP_TARGET_RELEASE, PTF_GROUP_STATUS
  FROM QSYS2.GROUP_PTF_INFO
  ORDER BY PTF_GROUP_NAME, PTF_GROUP_LEVEL DESC;

-- PTF group details for a specific group
SELECT PTF_GROUP_NAME, PTF_GROUP_DESCRIPTION,
       PTF_GROUP_LEVEL, PTF_GROUP_STATUS, COLLECTED_TIME
  FROM QSYS2.GROUP_PTF_INFO
  WHERE PTF_GROUP_NAME LIKE 'SF99%'
  ORDER BY PTF_GROUP_LEVEL DESC;

-- List individual PTFs for a product
SELECT PTF_IDENTIFIER, PTF_PRODUCT_ID, PTF_PRODUCT_DESCRIPTION,
       PTF_LOADED_STATUS, PTF_IPL_ACTION, PTF_STATUS_TIMESTAMP
  FROM QSYS2.PTF_INFO
  WHERE PTF_PRODUCT_ID = '5770SS1'
  ORDER BY PTF_STATUS_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- Find superseded PTFs
SELECT PTF_IDENTIFIER, PTF_PRODUCT_ID,
       PTF_SUPERSEDED_BY_PTF, PTF_LATEST_SUPERSEDING_PTF
  FROM QSYS2.PTF_INFO
  WHERE PTF_SUPERSEDED_BY_PTF IS NOT NULL
  ORDER BY PTF_STATUS_TIMESTAMP DESC
  FETCH FIRST 20 ROWS ONLY;

-- Check for defective PTFs
SELECT PARTITION_NAME, HOST_NAME, DEFECTIVE_PTF,
       APAR_ID, PRODUCT_ID, FIXING_PTF
  FROM SYSTOOLS.DEFECTIVE_PTF_CURRENCY;

-- PTFs pending IPL action
SELECT PTF_IDENTIFIER, PTF_PRODUCT_ID, PTF_IPL_ACTION,
       PTF_LOADED_STATUS, PTF_STATUS_TIMESTAMP
  FROM QSYS2.PTF_INFO
  WHERE PTF_IPL_ACTION IS NOT NULL
    AND PTF_IPL_ACTION <> 'NONE'
  ORDER BY PTF_STATUS_TIMESTAMP DESC;
