-- Db2 Mirror SQL Examples
-- Validated against live IBM i system

-- Check replication status for all IASPs
SELECT IASP_NAME, REPLICATION_STATE, REPLICATION_DETAIL,
       PRIMARY_NODE, SECONDARY_NODE, NRG_STATE,
       DEFAULT_INCLUSION_STATE, AUTO_RESUME, AUTO_TAKEOVER
  FROM QSYS2.MIRROR_INFO
  ORDER BY ASP_NUMBER;

-- View cluster topology
SELECT CLUSTER_NAME, DEVICE_DOMAIN_NAME,
       PRIMARY_NODE_NAME, PRIMARY_NODE_PRIMARY_IP,
       SECONDARY_NODE_NAME, SECONDARY_NODE_PRIMARY_IP
  FROM QSYS2.MIRROR_CLUSTER_INFO;

-- Health monitor configuration
SELECT IASP_NAME, AVAILABLE_STORAGE_THRESHOLD,
       CRITICAL_RESOURCE_CHECK_INTERVAL, RESOURCE_CHECK_INTERVAL
  FROM QSYS2.MIRROR_HEALTH_MONITOR_INFO;

-- Takeover IP addresses
SELECT GROUP_NAME, LOCAL_ADDRESS, PREFERRED_NODE,
       CURRENT_NODE, AUTO_SWITCHBACK
  FROM QSYS2.MIRROR_TAKEOVER_INFO
  ORDER BY GROUP_NAME;

-- NRG configuration and traffic
SELECT NRG_NAME, NRG_STATE, LINK_COUNT, ACTIVE_LINK_COUNT,
       OUTBOUND_RDMA_BYTES, INBOUND_RDMA_BYTES
  FROM QSYS2.NRG_INFO;

-- NRG link details
SELECT NRG_NAME, SOURCE_ADDRESS, TARGET_ADDRESS,
       LINK_STATE, LINK_PRIORITY, LINK_IN_USE
  FROM QSYS2.NRG_LINK_INFO
  ORDER BY NRG_NAME, LINK_PRIORITY;

-- RDMA link traffic and errors
SELECT SOURCE_ADDRESS, TARGET_ADDRESS, LINK_STATE,
       OUTBOUND_RDMA_BYTES, INBOUND_RDMA_BYTES,
       LINK_FAILURES, DROPPED_PACKETS
  FROM QSYS2.RDMA_LINK_INFO
  ORDER BY OUTBOUND_RDMA_BYTES DESC;

-- Replication criteria rules
SELECT RULE_IDENTIFIER, INCLUSION_STATE, APPLY_STATE,
       IASP_NAME, LIBRARY_NAME, OBJECT_TYPE, OBJECT_NAME
  FROM QSYS2.REPLICATION_CRITERIA_INFO
  ORDER BY IASP_NAME, LIBRARY_NAME;

-- Flight recorder configuration
SELECT ARCHIVE_RETENTION_DAY_COUNT, MAX_SYSBAS_PERCENTAGE,
       FLIGHT_RECORDER_LOGGING_LEVEL, RCL_LOGGING_LEVEL,
       RESYNC_LOGGING_LEVEL
  FROM QSYS2.MIRROR_FLIGHT_RECORDER_INFO;

-- Mirror version list
SELECT VERSION_GROUP, VERSION_NAME, STATE,
       ACTIVE_VERSION, PRIMARY_VERSION, SECONDARY_VERSION
  FROM QSYS2.MIRROR_VERSION_LIST
  ORDER BY ENTRY_NUMBER;
