-- System Health SQL Examples
-- Validated against live IBM i system

-- System status overview
SELECT ELAPSED_CPU_USED, AVERAGE_CPU_UTILIZATION,
       MAIN_STORAGE_SIZE, SYSTEM_ASP_USED,
       TOTAL_JOBS_IN_SYSTEM, ACTIVE_JOBS_IN_SYSTEM,
       HOST_NAME, PARTITION_NAME
  FROM TABLE(QSYS2.SYSTEM_STATUS(RESET_STATISTICS => 'YES')) X;

-- Real-time CPU activity
SELECT AVERAGE_CPU_RATE, AVERAGE_CPU_UTILIZATION,
       MINIMUM_CPU_UTILIZATION, MAXIMUM_CPU_UTILIZATION
  FROM TABLE(QSYS2.SYSTEM_ACTIVITY_INFO());

-- Memory pool status with paging
SELECT POOL_NAME, SYSTEM_POOL_ID, CURRENT_SIZE, DEFINED_SIZE,
       MAXIMUM_ACTIVE_THREADS, CURRENT_THREADS,
       ELAPSED_DATABASE_FAULTS, ELAPSED_NON_DATABASE_FAULTS
  FROM TABLE(QSYS2.MEMORY_POOL(RESET_STATISTICS => 'YES')) X
  ORDER BY SYSTEM_POOL_ID;

-- Disk unit capacity and usage
SELECT UNIT_NUMBER, ASP_NUMBER, UNIT_STORAGE_CAPACITY,
       UNIT_SPACE_AVAILABLE, PERCENT_USED,
       DISK_TYPE, RESOURCE_STATUS
  FROM QSYS2.SYSDISKSTAT
  ORDER BY ASP_NUMBER, UNIT_NUMBER;

-- ASP capacity and thresholds
SELECT ASP_NUMBER, DEVICE_DESCRIPTION_NAME,
       TOTAL_CAPACITY, TOTAL_CAPACITY_AVAILABLE,
       STORAGE_THRESHOLD_PERCENTAGE, NUMBER_OF_DISK_UNITS
  FROM QSYS2.ASP_INFO
  ORDER BY ASP_NUMBER;

-- System limits above 80% used
SELECT LIMIT_CATEGORY, LIMIT_TYPE, SIZING_NAME,
       CURRENT_VALUE, MAXIMUM_VALUE,
       DECIMAL(CURRENT_VALUE * 100.0 / MAXIMUM_VALUE, 7, 2) AS PCT_USED
  FROM QSYS2.SYSLIMITS
  WHERE MAXIMUM_VALUE > 0
    AND DECIMAL(CURRENT_VALUE * 100.0 / MAXIMUM_VALUE, 7, 2) >= 80
  ORDER BY PCT_USED DESC;

-- Established TCP connections
SELECT CONNECTION_TYPE, REMOTE_ADDRESS, REMOTE_PORT,
       LOCAL_ADDRESS, LOCAL_PORT, IDLE_TIME,
       BYTES_SENT_REMOTELY, BYTES_RECEIVED_LOCALLY
  FROM QSYS2.NETSTAT_INFO
  WHERE TCP_STATE = 'ESTABLISHED'
  ORDER BY BYTES_SENT_REMOTELY DESC
  FETCH FIRST 50 ROWS ONLY;

-- Count remote connections (excluding loopback)
SELECT COUNT(REMOTE_ADDRESS) AS REMOTE_CONNECTIONS
  FROM QSYS2.NETSTAT_INFO
  WHERE TCP_STATE = 'ESTABLISHED'
    AND REMOTE_ADDRESS != '::1'
    AND REMOTE_ADDRESS != '127.0.0.1';
