-- Librarian SQL Examples
-- Validated against live IBM i system

-- Complete library list
SELECT ORDINAL_POSITION, SCHEMA_NAME, SYSTEM_SCHEMA_NAME,
       TYPE, TEXT_DESCRIPTION
  FROM QSYS2.LIBRARY_LIST_INFO
  ORDER BY ORDINAL_POSITION;

-- System portion of library list
SELECT ORDINAL_POSITION, SCHEMA_NAME, SYSTEM_SCHEMA_NAME,
       TYPE, TEXT_DESCRIPTION
  FROM QSYS2.LIBRARY_LIST_INFO
  WHERE TYPE = 'SYSTEM'
  ORDER BY ORDINAL_POSITION;

-- Library details via OBJECT_STATISTICS
SELECT OBJNAME, OBJOWNER, OBJTYPE, OBJATTRIBUTE,
       OBJSIZE, OBJCREATED, OBJTEXT
  FROM TABLE(QSYS2.OBJECT_STATISTICS('QSYS', '*LIB', 'QGPL'));

-- Objects in a library
SELECT OBJNAME, OBJTYPE, OBJATTRIBUTE, OBJOWNER,
       OBJSIZE, OBJCREATED, OBJTEXT
  FROM TABLE(QSYS2.OBJECT_STATISTICS('QGPL', '*ALL'))
  ORDER BY OBJNAME
  FETCH FIRST 50 ROWS ONLY;

-- Authorization lists
SELECT AUTHORIZATION_LIST, SYSTEM_OBJECT_SCHEMA,
       SYSTEM_OBJECT_NAME, SYSTEM_OBJECT_TYPE, OBJECT_OWNER
  FROM QSYS2.AUTHORIZATION_LIST_INFO
  ORDER BY AUTHORIZATION_LIST
  FETCH FIRST 50 ROWS ONLY;

-- Authorization list users
SELECT AUTHORIZATION_LIST, AUTHORIZATION_NAME, OBJECT_AUTHORITY,
       DATA_READ, DATA_ADD, DATA_UPDATE, DATA_DELETE, DATA_EXECUTE
  FROM QSYS2.AUTHORIZATION_LIST_USER_INFO
  ORDER BY AUTHORIZATION_LIST, AUTHORIZATION_NAME
  FETCH FIRST 50 ROWS ONLY;

-- Object privileges for a library
SELECT AUTHORIZATION_NAME, OBJECT_AUTHORITY, OWNER,
       DATA_READ, DATA_ADD, DATA_UPDATE, DATA_DELETE, DATA_EXECUTE
  FROM QSYS2.OBJECT_PRIVILEGES
  WHERE SYSTEM_OBJECT_SCHEMA = 'QSYS'
    AND SYSTEM_OBJECT_NAME = 'QGPL'
    AND OBJECT_TYPE = '*LIB';
