-- Backup & Recovery Examples for IBM i SQL Services
-- Category: BACKUP AND RECOVERY

-- 1. List all save files ordered by most recent
SELECT SAVE_FILE_LIBRARY, SAVE_FILE, SAVE_TIMESTAMP,
       OBJECTS_SAVED, LIBRARY_NAME, SAVE_COMMAND
  FROM QSYS2.SAVE_FILE_INFO
  ORDER BY SAVE_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- 2. Find save files for a specific library
SELECT SAVE_FILE_LIBRARY, SAVE_FILE, SAVE_TIMESTAMP,
       OBJECTS_SAVED, TARGET_RELEASE
  FROM QSYS2.SAVE_FILE_INFO
  WHERE LIBRARY_NAME = 'MYLIB'
  ORDER BY SAVE_TIMESTAMP DESC;

-- 3. Search all save files for a specific object
SELECT SAVE_FILE_LIBRARY, SAVE_FILE, LIBRARY_NAME,
       OBJECT_NAME, OBJECT_TYPE, SAVE_TIMESTAMP
  FROM QSYS2.SAVE_FILE_OBJECTS
  WHERE OBJECT_NAME = 'CUSTMAST'
  ORDER BY SAVE_TIMESTAMP DESC;

-- 4. Inspect contents of a specific save file
SELECT LIBRARY_NAME, OBJECT_NAME, OBJECT_TYPE,
       SAVE_TIMESTAMP, OBJECT_SIZE, OBJECT_OWNER
  FROM TABLE(QSYS2.SAVE_FILE_OBJECTS(
    SAVE_FILE => 'MYSAVF',
    SAVE_FILE_LIBRARY => 'MYLIB',
    OBJECT_TYPE_FILTER => '*ALL',
    DETAILED_INFO => 'ALL'))
  ORDER BY LIBRARY_NAME, OBJECT_NAME;

-- 5. Find programs saved from a library
SELECT OBJECT_NAME, OBJECT_TYPE, SAVE_TIMESTAMP, OBJECT_SIZE
  FROM TABLE(QSYS2.SAVE_FILE_OBJECTS(
    SAVE_FILE => 'MYSAVF',
    SAVE_FILE_LIBRARY => 'MYLIB',
    OBJECT_TYPE_FILTER => '*PGM',
    DETAILED_INFO => 'ALL'))
  ORDER BY OBJECT_NAME;

-- 6. Tape library device status
SELECT DEVICE_NAME, DEVICE_STATUS, RESOURCE_NAME,
       DEVICE_TYPE, SERIAL_NUMBER
  FROM QSYS2.MEDIA_LIBRARY_INFO
  ORDER BY DEVICE_NAME;

-- 7. Available tape cartridges
SELECT VOLUME_IDENTIFIER, STATUS, CATEGORY,
       DEVICE_NAME, LOCATION
  FROM QSYS2.TAPE_CARTRIDGE_INFO
  WHERE STATUS = 'AVAILABLE'
  ORDER BY VOLUME_IDENTIFIER;
