-- Database Utility SQL Examples
-- Validated against live IBM i system

-- List files in a specific library
SELECT SYSTEM_TABLE_NAME AS FILE_NAME, SYSTEM_TABLE_SCHEMA AS LIBRARY,
       FILE_TYPE, SQL_OBJECT_TYPE, TEXT_DESCRIPTION,
       MAXIMUM_RECORD_LENGTH AS RECORD_LENGTH,
       NUMBER_MEMBERS, COMMON_CCSID AS CCSID
  FROM QSYS2.SYSFILES
  WHERE SYSTEM_TABLE_SCHEMA = 'MYLIB'
  ORDER BY SYSTEM_TABLE_NAME;

-- Partition statistics for a library
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_PARTITION,
       NUMBER_ROWS, NUMBER_DELETED_ROWS, DATA_SIZE,
       MAINTAINED_TEMPORARY_INDEX_SIZE,
       INSERT_OPERATIONS, UPDATE_OPERATIONS, DELETE_OPERATIONS,
       LAST_USED_TIMESTAMP
  FROM QSYS2.SYSPARTITIONSTAT
  WHERE TABLE_SCHEMA = 'MYLIB'
  ORDER BY DATA_SIZE DESC;

-- Member statistics
SELECT TABLE_SCHEMA, TABLE_NAME, SYSTEM_TABLE_MEMBER,
       NUMBER_ROWS, NUMBER_DELETED_ROWS, DATA_SIZE,
       LAST_USED_TIMESTAMP, LAST_CHANGE_TIMESTAMP
  FROM QSYS2.SYSMEMBERSTAT
  WHERE TABLE_SCHEMA = 'MYLIB'
  ORDER BY TABLE_NAME;

-- Object statistics for programs in a library
SELECT OBJNAME, OBJTYPE, OBJOWNER, OBJCREATED,
       LAST_USED_TIMESTAMP, DAYS_USED_COUNT, OBJSIZE, OBJTEXT
  FROM TABLE(QSYS2.OBJECT_STATISTICS('MYLIB', '*PGM'))
  ORDER BY CASE WHEN LAST_USED_TIMESTAMP IS NULL THEN 1 ELSE 0 END,
           LAST_USED_TIMESTAMP DESC
  FETCH FIRST 50 ROWS ONLY;

-- Find objects not used in over a year
SELECT OBJNAME, OBJTYPE, OBJSIZE, OBJTEXT,
       LAST_USED_TIMESTAMP, DAYS_USED_COUNT
  FROM TABLE(QSYS2.OBJECT_STATISTICS('MYLIB', '*ALL'))
  WHERE LAST_USED_TIMESTAMP IS NULL
     OR LAST_USED_TIMESTAMP < CURRENT_TIMESTAMP - 365 DAYS
  ORDER BY OBJSIZE DESC
  FETCH FIRST 50 ROWS ONLY;

-- Analyze catalog for inconsistencies
SELECT * FROM TABLE(QSYS2.ANALYZE_CATALOG(
  OPTION => 'DBXREF', LIBRARY_NAME => 'MYLIB'))
  ORDER BY 1;

-- Compare files between two libraries
SELECT * FROM TABLE(QSYS2.COMPARE_FILE(
  LIBRARY1 => 'TESTLIB', FILE1 => 'ORDERS',
  LIBRARY2 => 'PRODLIB', FILE2 => 'ORDERS'))
  ORDER BY ATTRIBUTE_NAME;

-- Find related objects (dependencies)
SELECT * FROM TABLE(SYSTOOLS.RELATED_OBJECTS(
  LIBRARY_NAME => 'MYLIB', FILE_NAME => 'CUSTMAST'))
  ORDER BY 1;

-- Validate data integrity
SELECT * FROM TABLE(SYSTOOLS.VALIDATE_DATA('MYLIB', 'CUSTMAST'))
  ORDER BY 1;

-- Tables with highest deleted row ratios
SELECT TABLE_SCHEMA, TABLE_NAME,
       NUMBER_ROWS, NUMBER_DELETED_ROWS,
       CASE WHEN NUMBER_ROWS + NUMBER_DELETED_ROWS > 0
         THEN INTEGER(NUMBER_DELETED_ROWS * 100 / (NUMBER_ROWS + NUMBER_DELETED_ROWS))
         ELSE 0 END AS DELETED_PCT,
       DATA_SIZE
  FROM QSYS2.SYSPARTITIONSTAT
  WHERE TABLE_SCHEMA = 'MYLIB'
    AND NUMBER_DELETED_ROWS > 0
  ORDER BY DELETED_PCT DESC
  FETCH FIRST 20 ROWS ONLY;
