-- Database Performance SQL Examples
-- Validated against live IBM i system

-- Index statistics for a library
SELECT INDEX_SCHEMA, INDEX_NAME, TABLE_NAME,
       COLUMN_NAMES, NUMBER_KEYS, INDEX_SIZE,
       QUERY_USE_COUNT, LAST_QUERY_USE,
       MAINTENANCE, UNIQUE
  FROM QSYS2.SYSINDEXSTAT
  WHERE TABLE_SCHEMA = 'MYLIB'
  ORDER BY QUERY_USE_COUNT DESC
  FETCH FIRST 50 ROWS ONLY;

-- Unused indexes (never used or not used in 90 days)
SELECT INDEX_SCHEMA, INDEX_NAME, TABLE_NAME,
       COLUMN_NAMES, INDEX_SIZE, MAINTENANCE,
       QUERY_USE_COUNT, LAST_QUERY_USE,
       INDEX_CREATE_TIMESTAMP
  FROM QSYS2.SYSINDEXSTAT
  WHERE TABLE_SCHEMA = 'MYLIB'
    AND INDEX_VALID = 'YES'
    AND (QUERY_USE_COUNT = 0 OR LAST_QUERY_USE IS NULL
         OR LAST_QUERY_USE < CURRENT_TIMESTAMP - 90 DAYS)
  ORDER BY INDEX_SIZE DESC;

-- MTI info for a specific table
SELECT TABLE_SCHEMA, TABLE_NAME,
       MTI_STATUS, MTI_CREATED, MTI_LAST_QUERY_USE,
       MTI_QUERY_USE_COUNT, MTI_SIZE,
       MTI_KEY_COLUMNS_ESTIMATED
  FROM TABLE(QSYS2.MTI_INFO('MYLIB', 'ORDERS'))
  ORDER BY MTI_QUERY_USE_COUNT DESC;

-- Database monitor status
SELECT MONITOR_ID, MONITOR_TYPE, MONITOR_STATUS,
       MONITOR_LIBRARY, MONITOR_FILE,
       NUMBER_ROWS, DATA_SIZE,
       MONITOR_JOB_FILTER
  FROM QSYS2.DATABASE_MONITOR_INFO
  ORDER BY MONITOR_STATUS, MONITOR_ID;

-- Query supervisor thresholds
SELECT THRESHOLD_NAME, THRESHOLD_TYPE, THRESHOLD_VALUE,
       DETECTION_FREQUENCY, LONG_COMMENT
  FROM QSYS2.QUERY_SUPERVISOR
  ORDER BY THRESHOLD_TYPE;

-- MQT statistics
SELECT MQT_SCHEMA, MQT_NAME, ENABLED,
       NUMBER_ROWS, MQT_SIZE,
       QUERY_USE_COUNT, LAST_QUERY_USE,
       REFRESH_TIME, MAINTENANCE
  FROM QSYS2.SYSMQTSTAT
  ORDER BY QUERY_USE_COUNT DESC;

-- Tables with highest MTI overhead
SELECT TABLE_SCHEMA, TABLE_NAME,
       NUMBER_ROWS, DATA_SIZE,
       MAINTAINED_TEMPORARY_INDEX_SIZE,
       NUMBER_DISTINCT_INDEXES
  FROM QSYS2.SYSPARTITIONSTAT
  WHERE TABLE_SCHEMA = 'MYLIB'
    AND MAINTAINED_TEMPORARY_INDEX_SIZE > 0
  ORDER BY MAINTAINED_TEMPORARY_INDEX_SIZE DESC
  FETCH FIRST 20 ROWS ONLY;

-- Most used indexes across a library
SELECT INDEX_NAME, TABLE_NAME,
       COLUMN_NAMES, QUERY_USE_COUNT,
       LAST_QUERY_USE, INDEX_SIZE
  FROM QSYS2.SYSINDEXSTAT
  WHERE TABLE_SCHEMA = 'MYLIB'
    AND QUERY_USE_COUNT > 0
  ORDER BY QUERY_USE_COUNT DESC
  FETCH FIRST 20 ROWS ONLY;

-- Index size summary by library
SELECT TABLE_SCHEMA,
       COUNT(*) AS INDEX_COUNT,
       SUM(INDEX_SIZE) AS TOTAL_INDEX_SIZE,
       SUM(CASE WHEN QUERY_USE_COUNT = 0 THEN INDEX_SIZE ELSE 0 END) AS UNUSED_INDEX_SIZE
  FROM QSYS2.SYSINDEXSTAT
  GROUP BY TABLE_SCHEMA
  ORDER BY TOTAL_INDEX_SIZE DESC
  FETCH FIRST 20 ROWS ONLY;
