-- Storage Examples for IBM i SQL Services
-- Category: STORAGE

-- 1. ASP overview — all ASPs with capacity and usage
SELECT ASP_NUMBER, DEVICE_DESCRIPTION_NAME, ASP_STATE,
       TOTAL_CAPACITY, CURRENT_USAGE_PERCENTAGE, STORAGE_TYPE,
       NUMBER_OF_DISK_UNITS
  FROM QSYS2.ASP_INFO
  ORDER BY ASP_NUMBER;

-- 2. Disk utilization — find highest-used disks
SELECT PERCENT_USED, RESOURCE_NAME,
       CASE WHEN UNIT_TYPE = 1 THEN 'SSD' ELSE 'DISK' END AS STORAGE_TYPE,
       ASP_NUMBER, CAPACITY
  FROM QSYS2.SYSDISKSTAT
  ORDER BY PERCENT_USED DESC
  FETCH FIRST 20 ROWS ONLY;

-- 3. Disk I/O performance — detailed with response times
SELECT RESOURCE_NAME, PERCENT_USED,
       SAMPLE_READS, SAMPLE_WRITES,
       SAMPLE_READ_RESPONSE_TIME, SAMPLE_WRITE_RESPONSE_TIME
  FROM TABLE(QSYS2.SYSDISKSTAT(RESET_STATISTICS => 'NO'))
  ORDER BY SAMPLE_WRITE_RESPONSE_TIME DESC
  FETCH FIRST 20 ROWS ONLY;

-- 4. Top temporary storage consumers
SELECT JOB_NAME, JOB_USER_NAME, JOB_NUMBER,
       BUCKET_CURRENT_SIZE, BUCKET_PEAK_SIZE
  FROM QSYS2.SYSTMPSTG
  WHERE JOB_STATUS = '*ACTIVE'
  ORDER BY BUCKET_CURRENT_SIZE DESC
  FETCH FIRST 20 ROWS ONLY;

-- 5. User storage consumption — top users
SELECT AUTHORIZATION_NAME, STORAGE_USED,
       MAXIMUM_STORAGE_ALLOWED, STORAGE_USED_BY_OWNED_OBJECTS
  FROM QSYS2.USER_STORAGE
  ORDER BY STORAGE_USED DESC
  FETCH FIRST 20 ROWS ONLY;

-- 6. Independent ASP jobs
SELECT IASP_NAME, JOB_NAME, JOB_USER_NAME, JOB_STATUS
  FROM QSYS2.ASP_JOB_INFO
  ORDER BY IASP_NAME, JOB_NAME;

-- 7. IASP vary operation history
SELECT IASP_NAME, OPERATION_TYPE, START_TIMESTAMP, END_TIMESTAMP,
       BIGINT(DURATION) AS DURATION_SECONDS, COMPLETION_STATUS
  FROM QSYS2.ASP_VARY_INFO
  ORDER BY START_TIMESTAMP DESC
  FETCH FIRST 20 ROWS ONLY;

-- 8. NVMe device health
SELECT RESOURCE_NAME, SERIAL_NUMBER, FIRMWARE_LEVEL,
       CONTROLLER_TEMPERATURE, PERCENTAGE_USED, AVAILABLE_SPARE
  FROM QSYS2.NVME_INFO
  ORDER BY PERCENTAGE_USED DESC;

-- 9. NVMe locking policy
SELECT RESOURCE_NAME, LOCKING_SUPPORTED, ELIGIBLE_POLICY, UNDER_POLICY
  FROM QSYS2.LOCKING_POLICY_INFO;
