-- Application Examples for IBM i SQL Services
-- Category: APPLICATION

-- 1. List CL commands in a specific library with threadsafe info
SELECT COMMAND_NAME, COMMAND_PROCESSING_PROGRAM_LIBRARY,
       COMMAND_PROCESSING_PROGRAM, THREADSAFE, PROXY_COMMAND,
       TEXT_DESCRIPTION
  FROM QSYS2.COMMAND_INFO
  WHERE COMMAND_LIBRARY = 'QSYS'
  ORDER BY COMMAND_NAME
  FETCH FIRST 50 ROWS ONLY;

-- 2. Find data areas in a library with their current values
SELECT DATA_AREA_NAME, DATA_AREA_TYPE, DATA_AREA_LENGTH,
       DATA_AREA_VALUE, TEXT_DESCRIPTION
  FROM QSYS2.DATA_AREA_INFO
  WHERE DATA_AREA_LIBRARY = 'QGPL'
  ORDER BY DATA_AREA_NAME;

-- 3. Targeted data area lookup by name using the library list
SELECT DATA_AREA_LIBRARY, DATA_AREA_NAME, DATA_AREA_TYPE,
       DATA_AREA_LENGTH, DATA_AREA_VALUE, TEXT_DESCRIPTION
  FROM TABLE(QSYS2.DATA_AREA_INFO('QCMN', '*LIBL'));

-- 4. Data queues with the most pending messages
SELECT DATA_QUEUE_LIBRARY, DATA_QUEUE_NAME, DATA_QUEUE_TYPE,
       CURRENT_MESSAGES, MAXIMUM_MESSAGE_LENGTH,
       MAXIMUM_NUMBER_OF_MESSAGES, TEXT_DESCRIPTION
  FROM QSYS2.DATA_QUEUE_INFO
  ORDER BY CURRENT_MESSAGES DESC
  FETCH FIRST 20 ROWS ONLY;

-- 5. List ILE programs in a library with language and activation group
SELECT PROGRAM_NAME, PROGRAM_TYPE, PROGRAM_LANGUAGE,
       ACTIVATION_GROUP, CREATION_TIMESTAMP, PROGRAM_SIZE,
       TEXT_DESCRIPTION
  FROM QSYS2.PROGRAM_INFO
  WHERE PROGRAM_LIBRARY = 'QGPL'
    AND PROGRAM_TYPE = 'ILE'
  ORDER BY PROGRAM_NAME;

-- 6. System-level environment variables
SELECT ENVIRONMENT_VARIABLE_NAME, ENVIRONMENT_VARIABLE_VALUE, CCSID
  FROM QSYS2.ENVIRONMENT_VARIABLE_INFO
  WHERE ENVIRONMENT_VARIABLE_TYPE = 'SYSTEM'
  ORDER BY ENVIRONMENT_VARIABLE_NAME;

-- 7. Registered exit programs for security exit points
SELECT EXIT_POINT_NAME, EXIT_PROGRAM_NUMBER, EXIT_PROGRAM_LIBRARY,
       EXIT_PROGRAM_NAME, EXIT_PROGRAM_DATA
  FROM QSYS2.EXIT_PROGRAM_INFO
  WHERE EXIT_POINT_NAME LIKE 'QIBM_QSY%'
  ORDER BY EXIT_POINT_NAME, EXIT_PROGRAM_NUMBER;

-- 8. Active watch sessions
SELECT SESSION_ID, WATCH_SESSION_TYPE, USER_ID,
       START_TIMESTAMP, WATCH_PROGRAM, WATCH_PROGRAM_LIBRARY
  FROM QSYS2.WATCH_INFO
  WHERE STATUS = 'ACTIVE'
  ORDER BY START_TIMESTAMP DESC;

-- 9. Binding directory entries for a specific binding directory
SELECT BINDING_DIRECTORY_LIBRARY, BINDING_DIRECTORY,
       ENTRY, ENTRY_LIBRARY, ENTRY_TYPE, ACTIVATION
  FROM QSYS2.BINDING_DIRECTORY_INFO
  WHERE BINDING_DIRECTORY = 'QC2LE'
    AND BINDING_DIRECTORY_LIBRARY = 'QSYS'
  ORDER BY ENTRY;

-- 10. Modules bound into an ILE program
SELECT PROGRAM_LIBRARY, PROGRAM_NAME, BOUND_MODULE,
       BOUND_MODULE_LIBRARY, MODULE_ATTRIBUTE,
       MODULE_CREATION_TIMESTAMP, SOURCE_FILE_LIBRARY,
       SOURCE_FILE, SOURCE_FILE_MEMBER
  FROM QSYS2.BOUND_MODULE_INFO
  WHERE PROGRAM_LIBRARY = 'QSYS'
  ORDER BY PROGRAM_NAME, BOUND_MODULE
  FETCH FIRST 30 ROWS ONLY;

-- 11. User space contents
SELECT *
  FROM TABLE(QSYS2.USER_SPACE(
    USER_SPACE => 'MYSPACE',
    USER_SPACE_LIBRARY => 'MYLIB'))
  FETCH FIRST 10 ROWS ONLY;

-- 12. User index inventory
SELECT USER_INDEX_LIBRARY, USER_INDEX_NAME, INDEX_TYPE,
       ENTRY_LENGTH, MAXIMUM_ENTRY_LENGTH,
       NUMBER_OF_ENTRIES_ADDED, NUMBER_OF_ENTRIES_REMOVED,
       TEXT_DESCRIPTION
  FROM QSYS2.USER_INDEX_INFO
  ORDER BY USER_INDEX_LIBRARY, USER_INDEX_NAME
  FETCH FIRST 20 ROWS ONLY;

-- 13. Program exports and imports for an ILE service program
SELECT PROGRAM_LIBRARY, PROGRAM_NAME, PROGRAM_TYPE,
       SYMBOL_NAME, SYMBOL_USAGE, DATA_ITEM_TYPE
  FROM TABLE(QSYS2.PROGRAM_EXPORT_IMPORT_INFO(
    PROGRAM_LIBRARY => 'QSYS',
    PROGRAM_NAME => 'QLEAWI',
    PROGRAM_TYPE => '*SRVPGM'))
  FETCH FIRST 30 ROWS ONLY;

-- 14. Active activation groups
SELECT ACTIVATION_GROUP_NAME, ACTIVATION_GROUP_NUMBER,
       PROGRAM_LIBRARY, PROGRAM_NAME, PROGRAM_TYPE
  FROM QSYS2.ACTIVATION_GROUP_INFO
  ORDER BY ACTIVATION_GROUP_NAME
  FETCH FIRST 30 ROWS ONLY;

-- 15. Call stack for the current job
SELECT ORDINAL_POSITION, PROGRAM_LIBRARY, PROGRAM_NAME,
       MODULE_NAME, PROCEDURE_NAME, STATEMENT_IDENTIFIERS,
       ACTIVATION_GROUP_NAME
  FROM TABLE(QSYS2.STACK_INFO('*'))
  ORDER BY ORDINAL_POSITION;
